routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::Resource('/author','AuthorController')->middleware(['web','auth']);
Route::Resource('/book','BookController')->middleware(['web','auth']);
Route::put('/book/onoff/{id}','BookController@onoff')->middleware(['web','auth'])->name('book.onoff');
Route::get('/book/image/{url}','BookController@getcoverimage')->name('book.image');
Route::put('/author/onoff/{id}','AuthorController@onoff')->middleware(['web','auth'])->name('author.onoff');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Storage;

class Book extends Model
{
    //
    protected $fillable=[
        'title','bookauthor','language','coverimage','pages','isbn_no','description',
    ];
    public function author(){
        return $this->belongsTo(Author::class);
    }
    public function setcoverimageAttribute($filename){
//        $file=Storage::url($filename);
//        return new Response($file,200);
        if($filename){
//            $image = Storage::disk('local')->get('storage/app/'.$filename);
            $image = Storage::get(asset('storage/app/'.$filename));
            return Response($image, 200);
        }
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Author;
use App\Book;
use Illuminate\Http\Response;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;


class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $book=Book::all()->where('created_by',Auth::id());
        return view('books.book_show',['book'=>$book]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('books.book_insert',['$a'=>Author::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' =>'required',
            'bookauthor' =>'required',
            'language'=>'required|string',
            'coverimage'=>'required',
            'pages'=>'required|numeric',
            'isbn_no'=>'required'
            ,'description'=>'required'
        ]);
        $b =  new Book;
        $file =$request->file('coverimage');
        $originalname = $file->getClientOriginalName();
        $filename= $file->storeAs('CoverImage/',$originalname);

        $b->title=$request->title;
        $b->bookauthor=$request->bookauthor;
        $b->language=$request->language;
        $b->coverimage=$filename;
        $b->pages=$request->pages;
        $b->isbn_no=$request->isbn_no;
        $b->description=$request->description;
        $b->created_by=Auth::id();
        $b->save();
        return redirect()->route('book.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('books.book_record',['book'=>Book::find($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book=Book::find($id);
//        dd($book);
        return view('books.book_update',['book'=>$book]);
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'title' =>'required',
            'bookauthor' =>'required',
            'language'=>'required|string',
            'coverimage'=>'required',
            'pages'=>'required |numeric',
            'isbn_no'=>'required|Digits:10'
            ,'description'=>'required'
        ]);
        $b= Book::find($id);
        $file =$request->file('coverimage');
        $originalname = $request['isbn_no'].'.'.$file->getClientOriginalExtension() ;
        $filename= $file->storeAs('CoverImage',$request['title'].''. $originalname);
        $b->title=$request->title;
        $b->bookauthor=$request->bookauthor;
        $b->language=$request->language;
        $b->coverimage=$filename;
        $b->pages=$request->pages;
        $b->isbn_no=$request->isbn_no;
        $b->description=$request->description;
        $b->update();

        return redirect()->route('book.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $b=Book::find($id);
        $b->delete();
        return redirect()->route('book.index');
    }
    public function onoff($id){
        $b=Book::find($id);
        if($b->status==1){
            $b->status=0;
            $b->update();
        }else{
            $b->status=1;
            $b->update();
        }
//        dd($b);
        return redirect()->route('book.index');
    }
}

resources/views/books/book_insert.blade.php
@extends('layouts.app')
@section('scripts')
    <script type="text/javascript" src="{{ asset('assets/js/books_insert_validation.js') }}" ></script>
@endsection
@include('messages')

    @section('content')
        <div class="container">
        <form method="post" action="{{route('book.store')}}" id="insform">
            @csrf

            <div class="form-group">
                <label for="">Title</label><span>*</span>
                <input type="text" class="form-control" name="title" id="title" aria-describedby="helpId" placeholder="">
                <span></span>
            </div>
            <div class="form-group">
                <label for="">Book Author</label><span>*</span>
                <select class="custom-select" name="bookauthor" id="bookauthor">
                 <option hidden>Select bookauthor</option>
                    {{$a=\App\Author::all()}}
                    @foreach($a as $aa)
                        <option value="{{$aa->id}}">{{$aa->fullname}}</option>
                    @endforeach
                </select>
                <span></span>
            </div>
            <div class="form-group">
                <label for="">Language</label><span>*</span>
              <input type="text" class="form-control" name="language" id="language" aria-describedby="helpId" placeholder="">
              <span></span>
            </div>
            <div class="form-group">
                <label for="">Pages</label><span>*</span>
              <input type="text" class="form-control" name="pages" id="pages" aria-describedby="helpId" placeholder="">
              <span></span>
            </div>
            <div class="form-group">
                <label for="">Cover Image</label><span>*</span>
              <input type="file" class="form-control" name="coverimage" id="coverimage" aria-describedby="helpId" placeholder="">
              <span></span>
            </div>

            <div class="form-group">
                <label for="">ISBN No.</label><span>*</span>
              <input type="integer" class="form-control" name="isbn_no" id="isbn_no" aria-describedby="helpId" placeholder="">
              <span></span>
            </div>
            <div class="form-group">
                <label for="">Description</label>
                <textarea class="form-control" name="description" id="description" rows="3"></textarea>
                <span></span>
            </div>
            <button type="submit" class="btn btn-primary"name="btninsert">Insert</button>
            </form>
            </div>
    @endsection

resources/views/books/book_record.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div>
        <a class="btn btn-primary" name="insert" href="{{route('book.create')}}">INSERT</a>
    </div>
    <table class='table table-striped table-dark'>
        <tr>
            <th>Title</th>
            <th>Book Author</th>
            <th>Coverimage</th>
            <th>Language</th>
            <th>Pages</th>
            <th>Isbn No</th>
            <th>description</th>
            <th>status</th><th>Update</th><th>Delete</th><th>Home</th></tr>

            <tr>
                <td>{{$book->Title}}</td>
                <td>{{$book->bookauthor}}</td>
                <td><img src="{{$book->coverimage}}"></td>
                <td>{{$book->language}}</td>
                <td>{{$book->pages}}</td>
                <td>{{$book->isbn_no}}</td>
                <td>{{$book->description}}</td>
                <td>{{$book->status}}</td>
{{--                <td><a class='btn btn-primary' name='insert' href='/book/{{$book->id}}/edit/'>Update</a></td>--}}
                <td><a class='btn btn-primary' name='insert' href="{{route('book.edit',['book'=>$book->id])}}">Update</a></td>
                <td>
                    <form action='{{route('book.destroy',['book'=>$book->id])}}' method="post">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger" >Delete</button>
                    </form>
                </td>
                <td><a class='btn btn-primary' name='show' href="{{route('book.index',['book'=>$book->id])}}">Home</a></td></tr>
    </table>

</div>
@endsection

resources/views/books/book_show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div>
        <a class="btn btn-primary" name="insert" href="{{route('book.create')}}">INSERT</a>
    </div>
    <table class='table table-striped table-dark'>
        <tr>
            <th>Title</th>
            <th>Book Author</th>
            <th>Coverimage</th>
            <th>Language</th>
            <th>Pages</th>
            <th>Isbn No</th>
            <th>description</th>
            <th>status</th><th>Update</th><th>Delete</th><th>Home</th><th>Home</th></tr>

        @foreach( $book as $book)
            <tr>
                <td>{{$book->Title}}</td>
                <td>{{$book->bookauthor}}</td>
                <td><img src="{{asset('storage/app/'.$book->cover_image)}}">
                    </td>
                <td>{{$book->language}}</td>
                <td>{{$book->pages}}</td>
                <td>{{$book->isbn_no}}</td>
                <td>{{$book->description}}</td>
                <td>{{$book->status}}</td>

{{--                <td><a class='btn btn-primary' name='insert' href='/book/{{$book->id}}/edit/'>Update</a></td>--}}
                <td><a class='btn btn-primary' name='insert' href="{{route('book.edit',['book'=>$book->id])}}">Update</a></td>
                <td>
                    <form action='{{route('book.destroy',['book'=>$book->id])}}' method="post">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger" >Delete</button>
                    </form>
                </td>
                <td><a class='btn btn-primary' name='show' href="{{route('book.show',['book'=>$book->id])}}">Show</a></td>
                <td>@if($book->status==1)
                        <form action='/book/onoff/{{$book->id}}' method="post">
                            @csrf
                            @method('put')
                            <button type="submit" class="btn btn-success">Active</button>
                        </form>
                        @endif
                    @if($book->status==0)
                        <form action='/book/onoff/{{$book->id}}' method="post">
                            @csrf
                            @method('put')
                            <button type="submit" class="btn btn-danger">Inactive</button>
                        </form>
                    @endif
                </td></tr>
        @endforeach
    </table>

</div>
@endsection

resources/views/books/book_update.blade.php
@extends('layouts.app')
@section('scripts')
    <script type="text/javascript" src="{{ asset('assets/js/books_update_validation.js') }}" defer></script>
@endsection
@include('messages')

@section('content')
    <div class="container">
        <form method="post" action="{{route('book.update',[$book->id])}}" id="updateform" enctype="multipart/form-data">
            @csrf
            @method('put')
            <div class="form-group">
                <label for="">Title</label><span>*</span>

                <input type="text" class="form-control" name="title" id="title" value="{{$book->Title}}" aria-describedby="helpId" placeholder="">
                <span></span>
            </div>
            <div class="form-group">
                <label for="">Book Author</label><span>*</span>
                <select class="custom-select" name="bookauthor" id="bookauthor">
                    <option hidden>Select bookauthor</option>
                    <option value="{{$book->bookauthor}}" selected>{{\App\Author::find($book->bookauthor)->fullname}}</option>
                    {{$a= \App\Author::all()->except($book->bookauthor)}}
                    @foreach($a as $a)
                        <option value="{{$a->id}}">{{$a->fullname}}</option>
                    @endforeach
                </select>
                <span></span>
            </div>
            <div class="form-group">
                <label for="">Language</label><span>*</span>
                <input type="text" class="form-control" name="language" id="language" value="{{$book->language}}" aria-describedby="helpId" placeholder="">
                <span></span>
            </div>
            <div class="form-group">
                <label for="">Pages</label><span>*</span>
                <input type="text" class="form-control" name="pages" id="pages" value="{{$book->pages}}" aria-describedby="helpId" placeholder="">
                <span></span>
            </div>
            <div class="form-group">
                @if(Storage::disk('local')->has($book['title'].'-'.$book['id'].'.jpg'))
                    <section class="row">
                        <div class="col-md-4">
                            <img src="{{route('account.image',['filename'=>$book->title . '-'. $book->id()])}}">
                        </div>
                    </section>
                @endif
                <label for="">Cover Image</label><span>*</span>
                <input type="file" class="form-control" name="coverimage" id="coverimage" value="{{$book->coverimage}}" aria-describedby="helpId" placeholder="">
                <span></span>
            </div>

            <div class="form-group">
                <label for="">ISBN No.</label><span>*</span>
                <input type="text" class="form-control" name="isbn_no" value="{{$book->isbn_no}}" id="isbn_no" aria-describedby="helpId" placeholder="">
                <span></span>
            </div>
            <div class="form-group">
                <label for="">Description</label>
                <textarea class="form-control" name="description" id="description" rows="3">{{$book->description}}</textarea>
                <span></span>
            </div>
            <button type="submit" class="btn btn-primary"name="btninsert">Insert</button>
        </form>
    </div>

@endsection