routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::Resource('/author','AuthorController')->middleware(['web','auth']);
Route::Resource('/book','BookController')->middleware(['web','auth']);
Route::put('/book/onoff/{id}','BookController@onoff')->middleware(['web','auth'])->name('book.onoff');
Route::get('/book/image/{url}','BookController@getcoverimage')->name('book.image');
Route::put('/author/onoff/{id}','AuthorController@onoff')->middleware(['web','auth'])->name('author.onoff');

app/Author.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    //
    protected $fillable=[
       'id', 'fullname',	'dob',	'phone',	'gender',	'address',	'description',
    ];
    public function authors(){
        return $this->hasMany(Book::class);
}
}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use App\Author;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;

class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $author=Author::all();
        return view('authors.author_show',['author'=>$author]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('authors.author_insert');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'fullname'=>'required',
            'dob'=>'required|Date',
            'phone'=>'numeric|required',
            'gender'=>'required' ,
            'address'=>'required',
            'description'=>'required',
        ]);

        Author::create($request->all());
        return redirect()->route('author.show');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,$id)
    {
//        Author::create($request->all());
        return view('authors.author_record',['author'=>Author::find($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $author=Author::find($id);
        return view('authors.author_update',['author'=>$author]);
        //
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'fullname'=>'required',
            'dob'=>'bail|required|Date',
            'phone'=>'bail|required|numeric|digits:10',
            'gender'=>'required' ,
            'address'=>'required',
            'description'=>'required',
        ]);
        $a= Author::find($id);
        $a->update($request->all());
        return redirect()->route('author.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $a=Author::find($id);
        $a->delete();
        return redirect()->route('author.index');
        //
    }
    public function onoff($id){
        $a=Author::find($id);
        if($a->status==1){
            $a->status=0;
            $a->update();
        }else{
            $a->status=1;
            $a->update();
        }
//        dd($b);
        return redirect()->route('author.index');
    }
}

resources/views/authors/author_insert.blade.php
@extends('layouts.app')
@section('scripts')
    <script src="{{ asset('js/author_insert_validations.js') }}" defer></script>

@endsection
@include('messages')
    @section('content')
    <div class="container sf">
        <form method="post" action="{{route('author.store')}}" id="insform">
@csrf
            <div class="form-group">
                <label for="">Full name</label><span>*</span>
                <input type="text" class="form-control" name="fullname" id="fullname" aria-describedby="helpId" placeholder="">
            </div>

            <div class="form-group">
                <label for="">DOB</label><span>*</span>
                  <input type="date" class="form-control" name="dob" id="dob" aria-describedby="helpId" placeholder="">

            </div>

            <div class="form-group">
                <label for="">Gender</label><span>*</span>
                    <select class="custom-select" name="gender" id="gender">
                        <option hidden>Select Gender</option>
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                    </select>

            </div>
            <div class="form-group">
                <label for="">Address</label><span>*</span>
                  <textarea class="form-control" name="address" id="address" rows="3"></textarea>
            </div>
            <div class="form-group">
                <label for="">Phone</label><span>*</span>
                  <input type="text" class="form-control" name="phone" id="phone" aria-describedby="helpId" placeholder="">
            </div>
            <div class="form-group">
                <label for="">Description</label>
                <textarea class="form-control" name="description" id="description" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary"name="btninsert">Insert</button>
            </form>
    </div>
    @endsection

resources/views/authors/author_record.blade.php
@extends('layouts.app')
@section('content')
<div class="container">

    <table class='table table-striped table-dark'>
        <tr>
            <th>Fullname</th><td>{{$author->fullname}}</td></tr>
        <tr><th>DOB</th> <td>{{$author->dob}}</td></tr>
            <tr><th>GENDER</th><td>{{$author->gender}}</td></tr>
            <tr><th>address</th><td>{{$author->address}}</td></tr>
            <tr><th>phone</th><td>{{$author->phone}}</td></tr>
            <tr><th>description</th><td>{{$author->description}}</td></tr>
            <tr><th>status</th><td>{{$author->status}}</td></tr>
        <tr><td>Insert</td><td colspan="2"><div class="col-sm-4 d-flex flex-column justify-content-center"> <a class='btn btn-primary' name='insert' href="{{route('author.edit',['author'=>$author->id])}}">Update</a>
                </div></td></tr>
        <tr colspan="2"><td>Delete</td><td><div class="col-sm-4 d-flex flex-column justify-content-center">
                    <form action='{{route('author.destroy',['author'=>$author->id])}}' method="post">
                @csrf
                @method('delete')
                <button type="submit" class="btn btn-danger " >Delete</button>
                    </form></div></td></tr>

        <tr colspan="2"><td>home</td><td colspan="2"><div class="col-sm-4 d-flex flex-column justify-content-center">
        <a class='btn btn-primary' name='insert' href="{{route('author.index',['author'=>$author->id])}}">Home</a></div></td></tr>

            <tr>





    </table>

</div>
@endsection

resources/views/authors/author_show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div>
        <a class="btn btn-primary" name="insert" href="{{route('author.create')}}">INSERT</a>
    </div>
    <table class='table table-striped table-dark'>
        <tr>
            <th>Fullname</th>
            <th>DOB</th>
            <th>GENDER</th>
            <th>address</th>
            <th>phone</th>
            <th>description</th>
            <th>status</th><th>Update</th><th>delete</th><th>Show</th><th>Active/Inactive</th></tr>

        @foreach( $author as $author)
            <tr>
                <td>{{$author->fullname}}</td>
                <td>{{$author->dob}}</td>
                <td>{{$author->gender}}</td>
                <td>{{$author->address}}</td>
                <td>{{$author->phone}}</td>
                <td>{{$author->description}}</td>
                <td>{{$author->status}}</td>
{{--                <td><a class='btn btn-primary' name='insert' href='/author/{{$author->id}}/edit/'>Update</a></td>--}}
                <td><a class='btn btn-primary' name='insert' href="{{route('author.edit',['author'=>$author->id])}}">Update</a></td>

                <td>
                    <form action='{{route('author.destroy',['author'=>$author->id])}}' method="post">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger " >Delete</button>
                    </form>
                </td>
                <td><a class='btn btn-primary' name='show' href="{{route('author.show',['author'=>$author->id])}}">Show</a></td>
                <td>@if($author->status==1)
                        <form action='/author/onoff/{{$author->id}}' method="post">
                            @csrf
                            @method('put')
                            <button type="submit" class="btn btn-success">Active</button>
                        </form>
                    @endif
                    @if($author->status==0)
                        <form action='/author/onoff/{{$author->id}}' method="post">
                            @csrf
                            @method('put')
                            <button type="submit" class="btn btn-danger">Inactive</button>
                        </form>
                    @endif
                </td></tr>
        @endforeach
    </table>

</div>
@endsection

resources/views/authors/author_update.blade.php
@extends('layouts.app')
@section('scripts')
    <script type="text/javascript" src="{{ asset('assets/js/author_update_validations.js') }}" defer></script>
@endsection
@include('messages')

    @section('content')
    <div class="container sf">
{{--        <form method="post" action="/author/{$author->id}" id="insform">--}}
        <form method="post" action="{{route('author.update',[$author->id])}}" id="updateform">
            @csrf
            @method('put')
            <div class="form-group">
                <label for="">Firstname</label><span>*</span>
                <input type="text" class="form-control" name="fullname" id="fullname" value="{{$author->fullname}}" aria-describedby="helpId" placeholder="">
                <span id="fnameErr"></span>
            </div>

            <div class="form-group">
                <label for="">DOB</label><span>*</span>
                  <input type="date" class="form-control" name="dob" id="dob" value="{{$author->dob}}" aria-describedby="helpId" placeholder="">
                  <span id="dobErr"></span>

            </div>

            <div class="form-group">
                <label for="">Gender</label><span>*</span>
                    <select class="custom-select" name="gender" id="gender">
                        <option selected value="{{$author->gender}}">{{$author->gender}}</option>
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                    </select>
                    <span id="genderErr"></span>

            </div>
            <div class="form-group">
                <label for="">Address</label><span>*</span>
                  <textarea class="form-control" name="address" id="address" rows="3">{{$author->address}}</textarea>
                  <span id="addressErr"></span>
            </div>
            <div class="form-group">
                <label for="">Phone</label><span>*</span>
                  <input type="number" class="form-control" name="phone" value="{{$author->phone}}" id="phone" aria-describedby="helpId" placeholder="">
                  <span id="phoneErr"></span>
            </div>
            <div class="form-group">
                <label for="">Description</label>
                <textarea class="form-control" name="desc" id="desc" rows="3">{{$author->description}}</textarea>
                <span id="descErr"></span>
            </div>
            <button type="submit" class="btn btn-primary"name="btnupdate">Update</button>
            </form>
    </div>
    @endsection